# Generated by Django 3.2 on 2023-06-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_unique_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
