# Generated by Django 3.2 on 2023-06-07 14:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[api.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
